### ISSUE TITLE
Flex 布局下的滚动问题

### ISSUE THREAD

**Issue by renjie-run** [renjie-run/blog#20]
### 场景
通过使用 flex 的方式，来让这个元素中的子元素上下左右居中。
```CSS
.father {
  width: 300px;
  height: 300px;
  margin: auto;
  border: 1px solid red;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: scroll;
}

.child {
  width: 50px;
  height: 50px;
  background-color: skyblue;
}
```
这种情况下效果如下，一点毛病都没有：
![image](https://user-images.githubusercontent.com/22960447/94223650-2224d980-ff23-11ea-8ceb-bacf23ca1933.png)

但是，当子元素的高度超出了父元素的高度（宽度亦同），这里就有问题了：不能滚动到顶部！
```CSS
.child {
  width: 50px;
  height: 500px;
  background-color: skyblue;
}
```

效果如下：
![image](https://user-images.githubusercontent.com/22960447/94223934-c1e26780-ff23-11ea-848a-6be854762154.png)

### 解决方案
目前从网上查找到了一种方案。

1. `margin: auto`
通过对使用了 flex 元素下的子元素使用 `margin: auto` 这个样式，便能解决这个问题。
```CSS
.child {
  width: 50px;
  height: 500px;
  background-color: skyblue;
  margin: auto;
}
```

处理过的效果图如下：
![image](https://user-images.githubusercontent.com/22960447/94224184-5220ac80-ff24-11ea-8b1c-14015f846cb0.png)

应该还有很多其他的解决方案，欢迎留言👏👏
